/* 
 * Nordea Account Information Services API v3
 *
 * Open Banking API
 *
 * OpenAPI spec version: 2.2.0-SNAPSHOT
 * Contact: support@nordeaopenbanking.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AccountsV3Api
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class AccountsV3ApiTests
    {
        private AccountsV3Api instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new AccountsV3Api();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AccountsV3Api
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' AccountsV3Api
            //Assert.IsInstanceOfType(typeof(AccountsV3Api), instance, "instance is a AccountsV3Api");
        }

        
        /// <summary>
        /// Test AccountDetailsUsingGET1
        /// </summary>
        [Test]
        public void AccountDetailsUsingGET1Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.AccountDetailsUsingGET1(id);
            //Assert.IsInstanceOf<AccountDetailsResponse> (response, "response is AccountDetailsResponse");
        }
        
        /// <summary>
        /// Test AccountListUsingGET1
        /// </summary>
        [Test]
        public void AccountListUsingGET1Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.AccountListUsingGET1();
            //Assert.IsInstanceOf<AccountListResponse> (response, "response is AccountListResponse");
        }
        
        /// <summary>
        /// Test TransactionListUsingGET1
        /// </summary>
        [Test]
        public void TransactionListUsingGET1Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //string continuationKey = null;
            //DateTime? fromDate = null;
            //string language = null;
            //DateTime? toDate = null;
            //var response = instance.TransactionListUsingGET1(id, continuationKey, fromDate, language, toDate);
            //Assert.IsInstanceOf<TransactionListResponse> (response, "response is TransactionListResponse");
        }
        
    }

}
