/* 
 * Nordea Account Information Services API v3
 *
 * Open Banking API
 *
 * OpenAPI spec version: 2.2.0-SNAPSHOT
 * Contact: support@nordeaopenbanking.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Account number
    /// </summary>
    [DataContract]
    public partial class AccountNumber :  IEquatable<AccountNumber>, IValidatableObject
    {
        /// <summary>
        /// Type of account number
        /// </summary>
        /// <value>Type of account number</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum TypeEnum
        {
            
            /// <summary>
            /// Enum IBAN for value: IBAN
            /// </summary>
            [EnumMember(Value = "IBAN")]
            IBAN = 1,
            
            /// <summary>
            /// Enum BBANSE for value: BBAN_SE
            /// </summary>
            [EnumMember(Value = "BBAN_SE")]
            BBANSE = 2,
            
            /// <summary>
            /// Enum BBANDK for value: BBAN_DK
            /// </summary>
            [EnumMember(Value = "BBAN_DK")]
            BBANDK = 3
        }

        /// <summary>
        /// Type of account number
        /// </summary>
        /// <value>Type of account number</value>
        [DataMember(Name="_type", EmitDefaultValue=false)]
        public TypeEnum Type { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="AccountNumber" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AccountNumber() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AccountNumber" /> class.
        /// </summary>
        /// <param name="type">Type of account number (required).</param>
        /// <param name="value">Actual account number (required).</param>
        public AccountNumber(TypeEnum type = default(TypeEnum), string value = default(string))
        {
            // to ensure "type" is required (not null)
            if (type == null)
            {
                throw new InvalidDataException("type is a required property for AccountNumber and cannot be null");
            }
            else
            {
                this.Type = type;
            }
            // to ensure "value" is required (not null)
            if (value == null)
            {
                throw new InvalidDataException("value is a required property for AccountNumber and cannot be null");
            }
            else
            {
                this.Value = value;
            }
        }
        

        /// <summary>
        /// Actual account number
        /// </summary>
        /// <value>Actual account number</value>
        [DataMember(Name="value", EmitDefaultValue=false)]
        public string Value { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AccountNumber {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AccountNumber);
        }

        /// <summary>
        /// Returns true if AccountNumber instances are equal
        /// </summary>
        /// <param name="input">Instance of AccountNumber to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AccountNumber input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Type == input.Type ||
                    (this.Type != null &&
                    this.Type.Equals(input.Type))
                ) && 
                (
                    this.Value == input.Value ||
                    (this.Value != null &&
                    this.Value.Equals(input.Value))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Type != null)
                    hashCode = hashCode * 59 + this.Type.GetHashCode();
                if (this.Value != null)
                    hashCode = hashCode * 59 + this.Value.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
