/* 
 * Nordea Account Information Services API v3
 *
 * Open Banking API
 *
 * OpenAPI spec version: 2.2.0-SNAPSHOT
 * Contact: support@nordeaopenbanking.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AccountListResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AccountListResponseTests
    {
        // TODO uncomment below to declare an instance variable for AccountListResponse
        //private AccountListResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AccountListResponse
            //instance = new AccountListResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AccountListResponse
        /// </summary>
        [Test]
        public void AccountListResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AccountListResponse
            //Assert.IsInstanceOfType<AccountListResponse> (instance, "variable 'instance' is a AccountListResponse");
        }


        /// <summary>
        /// Test the property 'GroupHeader'
        /// </summary>
        [Test]
        public void GroupHeaderTest()
        {
            // TODO unit test for the property 'GroupHeader'
        }
        /// <summary>
        /// Test the property 'Response'
        /// </summary>
        [Test]
        public void ResponseTest()
        {
            // TODO unit test for the property 'Response'
        }

    }

}
