/* 
 * Nordea Account Information Services API v3
 *
 * Open Banking API
 *
 * OpenAPI spec version: 2.2.0-SNAPSHOT
 * Contact: support@nordeaopenbanking.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AccountDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AccountDetailsTests
    {
        // TODO uncomment below to declare an instance variable for AccountDetails
        //private AccountDetails instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AccountDetails
            //instance = new AccountDetails();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AccountDetails
        /// </summary>
        [Test]
        public void AccountDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AccountDetails
            //Assert.IsInstanceOfType<AccountDetails> (instance, "variable 'instance' is a AccountDetails");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Links'
        /// </summary>
        [Test]
        public void LinksTest()
        {
            // TODO unit test for the property 'Links'
        }
        /// <summary>
        /// Test the property 'AccountName'
        /// </summary>
        [Test]
        public void AccountNameTest()
        {
            // TODO unit test for the property 'AccountName'
        }
        /// <summary>
        /// Test the property 'AccountNumbers'
        /// </summary>
        [Test]
        public void AccountNumbersTest()
        {
            // TODO unit test for the property 'AccountNumbers'
        }
        /// <summary>
        /// Test the property 'AccountType'
        /// </summary>
        [Test]
        public void AccountTypeTest()
        {
            // TODO unit test for the property 'AccountType'
        }
        /// <summary>
        /// Test the property 'AvailableBalance'
        /// </summary>
        [Test]
        public void AvailableBalanceTest()
        {
            // TODO unit test for the property 'AvailableBalance'
        }
        /// <summary>
        /// Test the property 'Bank'
        /// </summary>
        [Test]
        public void BankTest()
        {
            // TODO unit test for the property 'Bank'
        }
        /// <summary>
        /// Test the property 'BookedBalance'
        /// </summary>
        [Test]
        public void BookedBalanceTest()
        {
            // TODO unit test for the property 'BookedBalance'
        }
        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Test]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }
        /// <summary>
        /// Test the property 'CreditLimit'
        /// </summary>
        [Test]
        public void CreditLimitTest()
        {
            // TODO unit test for the property 'CreditLimit'
        }
        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Test]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }
        /// <summary>
        /// Test the property 'LatestTransactionBookingDate'
        /// </summary>
        [Test]
        public void LatestTransactionBookingDateTest()
        {
            // TODO unit test for the property 'LatestTransactionBookingDate'
        }
        /// <summary>
        /// Test the property 'Product'
        /// </summary>
        [Test]
        public void ProductTest()
        {
            // TODO unit test for the property 'Product'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'ValueDatedBalance'
        /// </summary>
        [Test]
        public void ValueDatedBalanceTest()
        {
            // TODO unit test for the property 'ValueDatedBalance'
        }

    }

}
