/* 
 * Nordea Account Information Services API v3
 *
 * Open Banking API
 *
 * OpenAPI spec version: 2.2.0-SNAPSHOT
 * Contact: support@nordeaopenbanking.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DebitTransaction
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DebitTransactionTests
    {
        // TODO uncomment below to declare an instance variable for DebitTransaction
        //private DebitTransaction instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DebitTransaction
            //instance = new DebitTransaction();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DebitTransaction
        /// </summary>
        [Test]
        public void DebitTransactionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DebitTransaction
            //Assert.IsInstanceOfType<DebitTransaction> (instance, "variable 'instance' is a DebitTransaction");
        }


        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Test]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'BalanceAfterTransaction'
        /// </summary>
        [Test]
        public void BalanceAfterTransactionTest()
        {
            // TODO unit test for the property 'BalanceAfterTransaction'
        }
        /// <summary>
        /// Test the property 'BookingDate'
        /// </summary>
        [Test]
        public void BookingDateTest()
        {
            // TODO unit test for the property 'BookingDate'
        }
        /// <summary>
        /// Test the property 'CardNumber'
        /// </summary>
        [Test]
        public void CardNumberTest()
        {
            // TODO unit test for the property 'CardNumber'
        }
        /// <summary>
        /// Test the property 'CounterpartyAccount'
        /// </summary>
        [Test]
        public void CounterpartyAccountTest()
        {
            // TODO unit test for the property 'CounterpartyAccount'
        }
        /// <summary>
        /// Test the property 'CounterpartyName'
        /// </summary>
        [Test]
        public void CounterpartyNameTest()
        {
            // TODO unit test for the property 'CounterpartyName'
        }
        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Test]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }
        /// <summary>
        /// Test the property 'CurrencyRate'
        /// </summary>
        [Test]
        public void CurrencyRateTest()
        {
            // TODO unit test for the property 'CurrencyRate'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Test]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'Narrative'
        /// </summary>
        [Test]
        public void NarrativeTest()
        {
            // TODO unit test for the property 'Narrative'
        }
        /// <summary>
        /// Test the property 'OriginalCurrency'
        /// </summary>
        [Test]
        public void OriginalCurrencyTest()
        {
            // TODO unit test for the property 'OriginalCurrency'
        }
        /// <summary>
        /// Test the property 'OriginalCurrencyAmount'
        /// </summary>
        [Test]
        public void OriginalCurrencyAmountTest()
        {
            // TODO unit test for the property 'OriginalCurrencyAmount'
        }
        /// <summary>
        /// Test the property 'OwnMessage'
        /// </summary>
        [Test]
        public void OwnMessageTest()
        {
            // TODO unit test for the property 'OwnMessage'
        }
        /// <summary>
        /// Test the property 'PaymentDate'
        /// </summary>
        [Test]
        public void PaymentDateTest()
        {
            // TODO unit test for the property 'PaymentDate'
        }
        /// <summary>
        /// Test the property 'Reference'
        /// </summary>
        [Test]
        public void ReferenceTest()
        {
            // TODO unit test for the property 'Reference'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'TransactionDate'
        /// </summary>
        [Test]
        public void TransactionDateTest()
        {
            // TODO unit test for the property 'TransactionDate'
        }
        /// <summary>
        /// Test the property 'TransactionId'
        /// </summary>
        [Test]
        public void TransactionIdTest()
        {
            // TODO unit test for the property 'TransactionId'
        }
        /// <summary>
        /// Test the property 'TypeDescription'
        /// </summary>
        [Test]
        public void TypeDescriptionTest()
        {
            // TODO unit test for the property 'TypeDescription'
        }
        /// <summary>
        /// Test the property 'ValueDate'
        /// </summary>
        [Test]
        public void ValueDateTest()
        {
            // TODO unit test for the property 'ValueDate'
        }

    }

}
