/* 
 * Nordea Account Information Services API v3
 *
 * Open Banking API
 *
 * OpenAPI spec version: 2.2.0-SNAPSHOT
 * Contact: support@nordeaopenbanking.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ExternalRequestEchoV2
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ExternalRequestEchoV2Tests
    {
        // TODO uncomment below to declare an instance variable for ExternalRequestEchoV2
        //private ExternalRequestEchoV2 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ExternalRequestEchoV2
            //instance = new ExternalRequestEchoV2();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ExternalRequestEchoV2
        /// </summary>
        [Test]
        public void ExternalRequestEchoV2InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ExternalRequestEchoV2
            //Assert.IsInstanceOfType<ExternalRequestEchoV2> (instance, "variable 'instance' is a ExternalRequestEchoV2");
        }


        /// <summary>
        /// Test the property 'MessageIdentifier'
        /// </summary>
        [Test]
        public void MessageIdentifierTest()
        {
            // TODO unit test for the property 'MessageIdentifier'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Test]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

    }

}
