/* 
 * Nordea Account Information Services API v3
 *
 * Open Banking API
 *
 * OpenAPI spec version: 2.2.0-SNAPSHOT
 * Contact: support@nordeaopenbanking.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ExternalErrorResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ExternalErrorResponseTests
    {
        // TODO uncomment below to declare an instance variable for ExternalErrorResponse
        //private ExternalErrorResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ExternalErrorResponse
            //instance = new ExternalErrorResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ExternalErrorResponse
        /// </summary>
        [Test]
        public void ExternalErrorResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ExternalErrorResponse
            //Assert.IsInstanceOfType<ExternalErrorResponse> (instance, "variable 'instance' is a ExternalErrorResponse");
        }

        /// <summary>
        /// Test deserialize a ExternalErrorResponseV3 from type ExternalErrorResponse
        /// </summary>
        [Test]
        public void ExternalErrorResponseV3DeserializeFromExternalErrorResponseTest()
        {
            // TODO uncomment below to test deserialize a ExternalErrorResponseV3 from type ExternalErrorResponse
            //Assert.IsInstanceOf<ExternalErrorResponse>(JsonConvert.DeserializeObject<ExternalErrorResponse>(new ExternalErrorResponseV3().ToJson()));
        }
        /// <summary>
        /// Test deserialize a ExternalErrorResponseV2 from type ExternalErrorResponse
        /// </summary>
        [Test]
        public void ExternalErrorResponseV2DeserializeFromExternalErrorResponseTest()
        {
            // TODO uncomment below to test deserialize a ExternalErrorResponseV2 from type ExternalErrorResponse
            //Assert.IsInstanceOf<ExternalErrorResponse>(JsonConvert.DeserializeObject<ExternalErrorResponse>(new ExternalErrorResponseV2().ToJson()));
        }


    }

}
