/* 
 * Nordea Account Information Services API v3
 *
 * Open Banking API
 *
 * OpenAPI spec version: 2.2.0-SNAPSHOT
 * Contact: support@nordeaopenbanking.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ExternalErrorV2
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ExternalErrorV2Tests
    {
        // TODO uncomment below to declare an instance variable for ExternalErrorV2
        //private ExternalErrorV2 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ExternalErrorV2
            //instance = new ExternalErrorV2();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ExternalErrorV2
        /// </summary>
        [Test]
        public void ExternalErrorV2InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ExternalErrorV2
            //Assert.IsInstanceOfType<ExternalErrorV2> (instance, "variable 'instance' is a ExternalErrorV2");
        }


        /// <summary>
        /// Test the property 'HttpCode'
        /// </summary>
        [Test]
        public void HttpCodeTest()
        {
            // TODO unit test for the property 'HttpCode'
        }
        /// <summary>
        /// Test the property 'Request'
        /// </summary>
        [Test]
        public void RequestTest()
        {
            // TODO unit test for the property 'Request'
        }
        /// <summary>
        /// Test the property 'Failures'
        /// </summary>
        [Test]
        public void FailuresTest()
        {
            // TODO unit test for the property 'Failures'
        }

    }

}
