/* 
 * Nordea Account Information Services API v3
 *
 * Open Banking API
 *
 * OpenAPI spec version: 2.2.0-SNAPSHOT
 * Contact: support@nordeaopenbanking.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ExternalErrorResponseV2
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ExternalErrorResponseV2Tests
    {
        // TODO uncomment below to declare an instance variable for ExternalErrorResponseV2
        //private ExternalErrorResponseV2 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ExternalErrorResponseV2
            //instance = new ExternalErrorResponseV2();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ExternalErrorResponseV2
        /// </summary>
        [Test]
        public void ExternalErrorResponseV2InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ExternalErrorResponseV2
            //Assert.IsInstanceOfType<ExternalErrorResponseV2> (instance, "variable 'instance' is a ExternalErrorResponseV2");
        }


        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Test]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }
        /// <summary>
        /// Test the property 'GroupHeader'
        /// </summary>
        [Test]
        public void GroupHeaderTest()
        {
            // TODO unit test for the property 'GroupHeader'
        }

    }

}
