/* 
 * Nordea Account Information Services API v3
 *
 * Open Banking API
 *
 * OpenAPI spec version: 2.2.0-SNAPSHOT
 * Contact: support@nordeaopenbanking.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ExternalResponseHeaderV3
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ExternalResponseHeaderV3Tests
    {
        // TODO uncomment below to declare an instance variable for ExternalResponseHeaderV3
        //private ExternalResponseHeaderV3 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ExternalResponseHeaderV3
            //instance = new ExternalResponseHeaderV3();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ExternalResponseHeaderV3
        /// </summary>
        [Test]
        public void ExternalResponseHeaderV3InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ExternalResponseHeaderV3
            //Assert.IsInstanceOfType<ExternalResponseHeaderV3> (instance, "variable 'instance' is a ExternalResponseHeaderV3");
        }


        /// <summary>
        /// Test the property 'CreationDateTime'
        /// </summary>
        [Test]
        public void CreationDateTimeTest()
        {
            // TODO unit test for the property 'CreationDateTime'
        }
        /// <summary>
        /// Test the property 'HttpCode'
        /// </summary>
        [Test]
        public void HttpCodeTest()
        {
            // TODO unit test for the property 'HttpCode'
        }
        /// <summary>
        /// Test the property 'MessageIdentification'
        /// </summary>
        [Test]
        public void MessageIdentificationTest()
        {
            // TODO unit test for the property 'MessageIdentification'
        }
        /// <summary>
        /// Test the property 'MessagePagination'
        /// </summary>
        [Test]
        public void MessagePaginationTest()
        {
            // TODO unit test for the property 'MessagePagination'
        }

    }

}
