/* 
 * Nordea Account Information Services API v3
 *
 * Open Banking API
 *
 * OpenAPI spec version: 2.2.0-SNAPSHOT
 * Contact: support@nordeaopenbanking.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TransactionList
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TransactionListTests
    {
        // TODO uncomment below to declare an instance variable for TransactionList
        //private TransactionList instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TransactionList
            //instance = new TransactionList();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TransactionList
        /// </summary>
        [Test]
        public void TransactionListInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TransactionList
            //Assert.IsInstanceOfType<TransactionList> (instance, "variable 'instance' is a TransactionList");
        }


        /// <summary>
        /// Test the property 'Links'
        /// </summary>
        [Test]
        public void LinksTest()
        {
            // TODO unit test for the property 'Links'
        }
        /// <summary>
        /// Test the property 'ContinuationKey'
        /// </summary>
        [Test]
        public void ContinuationKeyTest()
        {
            // TODO unit test for the property 'ContinuationKey'
        }
        /// <summary>
        /// Test the property 'Transactions'
        /// </summary>
        [Test]
        public void TransactionsTest()
        {
            // TODO unit test for the property 'Transactions'
        }

    }

}
