/* 
 * Nordea Account Information Services API v3
 *
 * Open Banking API
 *
 * OpenAPI spec version: 2.2.0-SNAPSHOT
 * Contact: support@nordeaopenbanking.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Transaction
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TransactionTests
    {
        // TODO uncomment below to declare an instance variable for Transaction
        //private Transaction instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Transaction
            //instance = new Transaction();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Transaction
        /// </summary>
        [Test]
        public void TransactionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Transaction
            //Assert.IsInstanceOfType<Transaction> (instance, "variable 'instance' is a Transaction");
        }

        /// <summary>
        /// Test deserialize a CreditTransaction from type Transaction
        /// </summary>
        [Test]
        public void CreditTransactionDeserializeFromTransactionTest()
        {
            // TODO uncomment below to test deserialize a CreditTransaction from type Transaction
            //Assert.IsInstanceOf<Transaction>(JsonConvert.DeserializeObject<Transaction>(new CreditTransaction().ToJson()));
        }
        /// <summary>
        /// Test deserialize a DebitTransaction from type Transaction
        /// </summary>
        [Test]
        public void DebitTransactionDeserializeFromTransactionTest()
        {
            // TODO uncomment below to test deserialize a DebitTransaction from type Transaction
            //Assert.IsInstanceOf<Transaction>(JsonConvert.DeserializeObject<Transaction>(new DebitTransaction().ToJson()));
        }


    }

}
